// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddKeyboard implements addKeyboard operation.
//
// POST /keyboard
func (UnimplementedHandler) AddKeyboard(ctx context.Context, req *Keyboard) (r *Keyboard, _ error) {
	return r, ht.ErrNotImplemented
}

// GetKeyboard implements getKeyboard operation.
//
// GET /keyboard/{id}
func (UnimplementedHandler) GetKeyboard(ctx context.Context, params GetKeyboardParams) (r *Keyboard, _ error) {
	return r, ht.ErrNotImplemented
}

// KeyboardGet implements GET /keyboard operation.
//
// GET /keyboard
func (UnimplementedHandler) KeyboardGet(ctx context.Context) (r []Keyboard, _ error) {
	return r, ht.ErrNotImplemented
}
